### ISSUE TITLE
Add a primitive for securely zeroing memory

### ISSUE THREAD

**Issue by s-zanella** [FStarLang/kremlin#146] opened 2019-07-18 09:25 UTC
We need a primitive to scrub buffers storing secrets after they are no longer needed. E.g. to erase a Diffie-Hellman ephemeral secret key after computing the shared secret and thus minimize the time window the ephemeral key is stored in memory.

`LowStar.Buffer.fill b 0uy len` [will extract ](https://github.com/FStarLang/kremlin/issues/145) as `memset(b, 0U, sizeof b[0U])`, but a compiler can optimize a call to `memset` away if the written zeros are never read back.

Unfortunately, there is no complete solution to the problem of securely erasing secrets from memory. See [What you get is what you C](https://www.cl.cam.ac.uk/~rja14/Papers/whatyouc.pdf), [Erasing Sensitive Data - GNU libc manual](https://www.gnu.org/software/libc/manual/html_node/Erasing-Sensitive-Data.html) for why this is the case. 

But there are partial solutions for scrubbing known copies of secrets from memory. Some platforms provide functions that behave like `memset` but are guaranteed not to be eliminated by the compiler: [explicit_bzero](https://www.freebsd.org/cgi/man.cgi?query=explicit_bzero&sektion=3), [SecureZeroMemory](https://docs.microsoft.com/en-us/previous-versions/windows/desktop/legacy/aa366877(v%3Dvs.85)). The C11 standard defines [memset_s](https://port70.net/~nsz/c/c11/n1570.html#K.3.7.4.1) as an optional extension that behaves similarly. This feature request is for a primitive in `LowStar.Buffer` that KreMLin extracts as one of these functions.

**Comment by beurdouche** [comment] 2019-07-18 10:14
This is a good thing to track. The current solution in experimental HACL is to use the code below but it would be good to have standalone kremlin files for it:
https://github.com/jedisct1/libsodium/blob/master/src/libsodium/sodium/utils.c#L113

**Comment by msprotz** [comment] 2019-07-18 17:40
Thanks for the recap and the good pointers, Santiago and Benjamin. It's going to be hard to do something as good as libsodium.

The crux of the issue is that these things are so toolchain-dependent that a configure script seems at this stage inevitable. 
- SecureZeroMemory seems to be pretty widely supported on windows
- memset_s is not present on my linux machine and attempts to add it to GNU libc seem to have failed (https://patchwork.ozlabs.org/patch/421217/) -- is there any toolchain out there that supports it?
- explicit_bzero works on my linux machine (and seems to be a freebsd thing do)
- explicit_memset seens to be a netbsd thing

To detect support of these various features, we'd have to roll out the autoconfig business, something I've explicitly tried to avoid for kremlin (but maybe the time is ripe?). @beurdouche how did you deal with the variety of systems and platforms?

Alternatively, we could support only SecureZeroMemory (Windows), and explicit_bzero (else), meaning the file doesn't compile if explicit_bzero is not present. This should cover most of the platforms we care about, and we'll leave it up to consumers downstream to inform us about issues they encounter with that (will it break CCF?).

Note that we could potentially do things even more sophisticated than that, by exposing a secure allocation function for secrets, see https://lkml.org/lkml/2019/4/24/1864 for what's been happening recently in linux-land.

**Comment by msprotz** [comment] 2020-05-29 18:39
Fixed in https://github.com/project-everest/hacl-star/pull/302

**Closed by msprotz** 2020-05-29 18:39 UTC
Labels: enhancement
